### PR TITLE
Support for explicit IP addresses to filter

### PR DESCRIPTION
**Pull request by bmundt6**
Quick and dirty way to let one or two hosts through the filter (or, as in the example, allow all LAN traffic).

### CODE REVIEW

**Comment by mpdcampbell** [comment]
Thanks for the PR, this is a great feature to add! 

Adding this new EXTRA_IPS variable adds a couple of new possible cases that need accounted for now.
- EXTRA_IPS is listed in the docker-compose.yml but is empty 
(Causes an empty set of quotes "" to be added to IPList.conf, breaking the container)
- SUB_CODES and COUNTRY_CODES are empty but EXTRA_IPS is not empty 
(The container exits as the two location variables are empty, expected behaviour would be container runs with only the EXTRA_IPS in the filter)

I don't want to merge with main before adding catches for these cases. I've created a new branch feature/extra-ips, would you be happy to change the base branch on your PR to merge into this feature branch instead?

**Comment by bmundt6** [comment]
Great catch, thank you for reviewing! I will look into the former case; as to the latter, I don't necessarily consider this broken (if the goal were _only_ to apply an explicit IP allowlist/blocklist, there is already a Traefik middleware that can achieve that, so I'd still consider it a misconfiguration to have no country/subcodes).

**Comment by bmundt6** [comment]
Rebased and fixed! (with https://github.com/mpdcampbell/traefik-geoip-filter/pull/33/commits/dff1d4da6ac00b0d58c2d9bb65c195714bf7033e)

**Comment by mpdcampbell** [comment]
> I don't necessarily consider this broken (if the goal were _only_ to apply an explicit IP allowlist/blocklist, there is already a Traefik middleware that can achieve that, so I'd still consider it a misconfiguration to have no country/subcodes).

Good point, I'm happy to leave the behaviour as is.

> Rebased and fixed! (with [dff1d4d](https://github.com/mpdcampbell/traefik-geoip-filter/commit/dff1d4da6ac00b0d58c2d9bb65c195714bf7033e))

Thanks for making this change. Works on my end, I'll accept the PR, merge into main and update the image. 

Thanks for the feature add!

**Comment by mpdcampbell** [comment]
Clicked the wrong button and accidentally closed...

**Pull request merged**
